services:
    _defaults:
        autowire: true
        autoconfigure: true

    PrestaShop\CoreUpgradeBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/CoreUpgradeBundle.php'
